public enum AugmentId
{
    None = 0,
    MovementSpeedIncreaseCommon = 1,
    MovementSpeedIncreaseRare = 2,
    MovementSpeedIncreaseExtraordinary = 3,
    ChargedLongbowAoeUnlock = 4,
    DoubleArrowUnlock = 5,
    WallLootsUnlock = 6,
    ExtraAugmentSlotUnlock = 7,
    GlassCannonDoubleDamageHalveMaxHealth = 8,
    MaxHealthIncreasePercent = 9,
    ProjectileCount_PlusOneProjectiles = 11,
    ProjectileCount_PlusOneAndSpeed10Percent = 12,
    ProjectileCount_PlusOneAndSpeed15Percent = 13,
    DashUnluck = 15,
    DashCooldownReduce_Common_I = 16,
    DashCooldownReduce_Common_II = 17,
    DashCooldownReduce_Rare = 18,
    DashCooldownReduce_Extraordinary = 19,
    LuckIncrease_Common_I = 20,
    LuckIncrease_Common_II = 21,
    LuckIncrease_Common_III = 22,
    LuckIncrease_Rare = 23,
    LuckIncrease_Extraordinary = 24,
    HammerChargeReduceUnlock = 28,
    DashDistanceIncrease_Uncommon_I = 29,
    DashDistanceIncrease_Uncommon_II = 30,
    DashDistanceIncrease_Uncommon_III = 31,
    DashDistanceIncrease_Rare = 32,
    DashDistanceIncrease_Extraordinary = 33,
    DamageReduction_Common = 34,
    DamageReduction_Rare = 35,
    DamageReduction_Extraordinary = 36,
    HammerChargeDamageReductionUnlock = 37,
    HammerFreezeUnlock = 40,
    LongbowFreezeUnlock = 41,
    HammerAoeRadiusUnlock = 46,
    LongbowAoeRadius_Common = 47,
    LongbowAoeRadius_Rare = 48,
    LongbowAoeRadius_Extraordinary = 49,
    MaxHealthFlatIncrease_Common_I = 50,
    MaxHealthFlatIncrease_Common_II = 51,
    MaxHealthFlatIncrease_Common_III = 52,
    MaxHealthFlatIncrease_Common_IV = 53,
    HalfHealthBonusDamage = 54,
    FireArrowUnlock = 55,
    PoisonArrowUnlock = 56,
    CrossbowBoltPierce     = 57,
    CrossbowBoltBleed      = 58,
    HammerChargeUnlock              = 59,

    // ── Hammer Light Attack ───────────────────────────────────────────────────
    HammerLightDamageIncrease_Common        = 60,
    HammerLightDamageIncrease_Rare          = 61,
    HammerLightDamageIncrease_Extraordinary = 62,
    HammerLightAttackSpeedIncrease_Common   = 63,
    HammerLightAttackSpeedIncrease_Rare     = 64,

    // ── Hammer Slam (Heavy) ───────────────────────────────────────────────────
    HammerSlamCooldownReduceUnlock          = 65,

    // ── Crossbow Stat ─────────────────────────────────────────────────────────
    CrossbowAttackSpeedIncrease_Common        = 66,
    CrossbowAttackSpeedIncrease_Rare          = 67,
    CrossbowAttackSpeedIncrease_Extraordinary = 68,
    CrossbowDamageIncrease_Common             = 69,
    CrossbowDamageIncrease_Rare               = 70,
    CrossbowDamageIncrease_Extraordinary      = 71,

    // ── Crossbow Unlock ───────────────────────────────────────────────────────
    CrossbowBoltFireUnlock   = 72,
    CrossbowBoltPoisonUnlock = 73,

    // ── Genel Hasar ───────────────────────────────────────────────────────────
    OutgoingDamageIncrease_Common        = 74,
    OutgoingDamageIncrease_Rare          = 75,
    OutgoingDamageIncrease_Extraordinary = 76,
}
